# Stage 1: Build the application
FROM node:lts-alpine as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Create the runtime image
FROM node:lts-alpine
COPY --from=builder /usr/src/app/package*.json /
RUN npm install --only=production
COPY --from=builder /usr/src/app/dist /dist

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
